### PR TITLE
Fixed SET in SQLite 3

### PR DESCRIPTION
**Pull request by stoke**
I've noticed that #set doesn't work on SQLite 3 dialect because it's called without a context being set.

This patch should fix everything (yep, it's just one line of code :P)

### CODE REVIEW

**Comment by yawnt** [comment]
thanks.. @rsdoiel lgtm..

**Comment by rsdoiel** [comment]
Thanks!

**Comment by yawnt** [comment]
hey, how you doin? do you plan to keep working on sqlish? just wonderin

**Comment by rsdoiel** [comment]
Hello,

I'm doing well though not much time for outside programming.  I've been
using Sqlish in a work project. What it does now it pretty much what I need
for that use case (data migration/synchronization between MySQL and MongoDB
via Node). Not sure where to take it next with out a new real life use case
to help guide me.

How is your ORM going? If you know anyone who wants to contribute feel free
to invite them.

All the best,

Robert

**Pull request merged**
